CREATE TABLE IF NOT EXISTS `tab_referidos` (
  `id_documento` int(11) NOT NULL,
  `apellido1` text CHARACTER SET latin1 COLLATE latin1_spanish_ci NOT NULL,
  `apellido2` text CHARACTER SET latin1 COLLATE latin1_spanish_ci NOT NULL,
  `nombre1` text COLLATE utf8_spanish_ci NOT NULL,
  `nombre2` text COLLATE utf8_spanish_ci NOT NULL,
  `genero` text COLLATE utf8_spanish_ci NOT NULL,
  `fecnac` text COLLATE utf8_spanish_ci NOT NULL,
  `tipo_sang` text COLLATE utf8_spanish_ci NOT NULL,
  `tel_movil` decimal(11,0) DEFAULT NULL,
  `correo` text COLLATE utf8_spanish_ci,
  `direccion_res` text COLLATE utf8_spanish_ci,
  `municipio_res` text COLLATE utf8_spanish_ci,
  `dpto_vot` text COLLATE utf8_spanish_ci,
  `municipio_vot` text COLLATE utf8_spanish_ci,
  `puesto_vot` text COLLATE utf8_spanish_ci,
  `direccion_vot` text COLLATE utf8_spanish_ci,
  `mesa_vot` int(11) DEFAULT NULL,
  `fecha_insc` text COLLATE utf8_spanish_ci,
  `observacion` text COLLATE utf8_spanish_ci,
  `longitud` text COLLATE utf8_spanish_ci,
  `latitud` text COLLATE utf8_spanish_ci,
  `fecha_reg` datetime DEFAULT NULL,
  PRIMARY KEY (`id_documento`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;